# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeschool',
            name='badge',
            field=models.ImageField(upload_to='/Users/jose/webapps/joe/static/img/'),
        ),
    ]
