# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20161024_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeschool',
            name='badge',
            field=models.CharField(max_length=100),
        ),
    ]
