# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20161024_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='codeacademy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
    ]
