# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_codeacademy'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('budget', models.CharField(max_length=30)),
                ('start', models.CharField(max_length=30)),
                ('project', models.CharField(max_length=1000)),
            ],
        ),
    ]
