# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codeacademy',
            old_name='image',
            new_name='description',
        ),
    ]
